# Generated by Django 3.2.13 on 2022-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_equipment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='workout_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='workout_level',
            field=models.TextField(blank=True),
        ),
    ]
