# Generated by Django 3.2.13 on 2022-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220904_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_equipment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='workout_level',
            field=models.CharField(max_length=200),
        ),
    ]
